# Generated by Django 4.0.2 on 2022-02-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listening',
            name='date',
            field=models.DateField(verbose_name='Last Listened'),
        ),
    ]
