# Generated by Django 4.0.2 on 2022-02-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_listening_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img',
            field=models.CharField(max_length=250),
        ),
    ]
